### ISSUE TITLE
kutty-bootstrap: Alert

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/kutty#11]
Alerts should implement this Bootstrap component: https://getbootstrap.com/docs/4.6/components/alerts/

Alert components need some JavaScript to be added to be closeable. That should be the default.

Alerts can be of different kinds. How do we let the developer write which of these kinds to use?

One way is to use a keyword argument:
```python3
element1 = Alert("Task completed!", kind="success")
element2 = Alert("Something went wrong", kind="danger")  # should it be called error instead?
```

The other would be to have separate constructors for each:
```python3
element1 = SuccessAlert("Task Completed!")
element2 = DangerAlert("Something went wrong.")
```

Whatever naming or format we choose here, we should replicate it later for other elements such as `button`, `card`, etc.

**Comment by anandology** [comment]
How are you going to support `.alert-link` , `.alert-heading` and the close button?

**Comment by nikochiko** [comment]
1. `alert-link`: How about adding that class for all `Link` instances in `self.children` and in their children? Raw HTML won't change.
2. `alert-heading`:  How about a keyword argument that takes a heading? 
3. close button: That should be the default. I think a keyword flag like `closeable` should be good enough to customize it.

**Comment by anandology** [comment]
Zee

**Comment by nikochiko** [comment]
I think it might be better to structure this too in a similar fashion to [cards](#18) and other Kutty elements where we can add children to the parent element when it comes to data.
The presentation should be defined early and doesn't need to be changed later, but the main data should have the ability to be changed.

How about this instead?

```python3
from kutty import Link, html
from kutty.bootstrap import Alert

alert = Alert(title="Well done!", closeable=False)
alert.add(
    html.p(
      "You have successfully completed",
      Link("the challenge.", "/challenge-page")
    )
)
```

`alert.add` will look at the element and its children, if there are any of type `Link`, it will add the `alert-link` class to them.

**Comment by nikochiko** [comment]
Merged in https://github.com/pipalacademy/kutty/commit/6f21a3b50a0e3b04dc78554aa6e199ed6b47b54b
