### ISSUE TITLE
kutty-bootstrap: Card

### ISSUE THREAD

**Issue by nikochiko** [pipalacademy/kutty#18]
This is the bootstrap component to be used: https://getbootstrap.com/docs/4.6/components/card/

A card should have a `title`, `subtitle`, `text`, `image`, `header`, and `footer` in its constructor. This should be able to cover most of the use cases.

Note: needs a more thorough look.

**Comment by nikochiko** [comment]
Cards are a bit complicated because the different forms that they can be used in change the nature of the card completely.
While it is easy to make sense of a card component that takes an image, title, subtitle, and some other text, complexity arises when there is some content in the card body in addition to the text. Such as some action buttons. Additionally, there can be a header and a footer.

Even so, a card element that takes `header`, `image`, `title`, `subtitle`, `text`, `extra_body`, and `footer` could be okay. I'm a bit doubtful about calling it `extra_body` but I think that name makes sense, because it is in addition to the title, subtitle, and text.

There is also the case when a card appears and without any body element, there is directly content that is added to this element. This is used with flush list groups, for example in [this example](https://getbootstrap.com/docs/4.6/components/card/#list-groups).

For the image, there are three more cases - when the image is below the card body, overlayed on the card body, and beside the card body. I'm not yet sure how that can be abstracted well. 

A card can also be customized in terms of the background color, text color, and border color. The same is also true for other elements. I think we should decide on some set styles and then abstract in terms of that.

I will create an issue for that.

**Comment by nikochiko** [comment]
I'm keeping aside styling for the moment. Even for data, what would be the fields to accept and how to accept the data for each is not clear.
For example, when I say `card.add()` should that add to the card itself or the `card-body`. If it is added to card, how is it possible to add something to the `card-body`?

One way to get past this would be to expose the underlying structure and let the user add to `card.body`, `card.header`, or `card.footer`.

Each of them would be an element with a list of children. 

We can have a more concise abstraction on top of this that could use this interface under the hood.

**Comment by nikochiko** [comment]
How about this?

```python3
from kutty.bootstrap import Card

card = Card()
header = card.add_header("Featured")
body = card.add_body(title="Kutty", subtitle="Bootstrap cards with Kutty")
body.add_text("This is Kutty bootstrap and cards are very easy to create. The developer also gets control of what goes into the card and in what order.")
body.add_link("Reference", "https://example.com/reference")
body.add_link("GitHub", "https://github.com/pipalacademy/kutty")
card.add_footer("Last updated 10 minutes ago")
```

For a card with an image:

```python3
card = Card()

card.add(Image("https://example.com/image.jpg"))
body = card.add_body()
body.add_title("Kutty Demo")
body.add_subtitle("Images in Kutty cards")
body.add_text("It's only necessary to correctly order the elements to add images correctly to Kutty cards")
```

For a card with image at the bottom:

```python3
card = Card()

body = card.add_body(title="Advanced card usage", subtitle="Card with image at the bottom")
body.add(Image("https://example.com/image.jpg"))
```

The reason for going with this rather than with a style where there is only one body or one header is that then we have to make assumptions and do some magic behind the scenes.
For example, it could mean that a card initialized with the `title` keyword has to have a body associated with it but a card where it wasn't given shouldn't be. I tried to avoid that with this design.  

The other concern was that it makes it harder to accommodate cases when elements are added to the top or start of the card. We would have to have something like `add_before_body()` and `add_after_body()`, or `.before_body.add(...)` / `.after_body.add()`. Both seem more confusing than they should be. This is also consistent with the other Kutty elements where we `.add()` in order.

**Comment by anandology** [comment]
> from kutty.bootstrap import Card\n\ncard = Card()\nheader = card.add_header(\"Featured\")\nbody = card.add_body(title=\"Kutty\", subtitle=\"Bootstrap cards with Kutty\")\nbody.add_text(\"This is Kutty bootstrap and cards are very easy to create. The developer also gets control of what goes into the card and in what order.\")\nbody.add_link(\"Reference\", \"https://example.com/reference\")\nbody.add_link(\"GitHub\", \"https://github.com/pipalacademy/kutty\")\ncard.add_footer(\"Last updated 10 minutes ago

How about this instead?

```python
card = Card()
card.header << " Featured"
card.body << "This is kutty bootstrap and cards are easy to create."
card.body << Link("GitHub", href="https ://github.com/pipalacademy/kutty")
card.footer << "Last updated 10 minutes ago"
```

**Comment by nikochiko** [comment]
Okay, how do you:
1. Create a card with an image before the body? (like [this](https://getbootstrap.com/docs/4.6/components/card/#images))
2. Create a card with an image after the body? (like the second example in [this](https://getbootstrap.com/docs/4.6/components/card/#images-1))
3. Create a card with an image overlay? (like [this](https://getbootstrap.com/docs/4.6/components/card/#image-overlays))

**Comment by nikochiko** [comment]
What is the default value for `card.header` and `card.footer`, would that div be rendered as if nothing is added there?

**Comment by anandology** [comment]
header/footer may be skipped if no content is added to them.

**Comment by nikochiko** [comment]
Merged in https://github.com/pipalacademy/kutty/commit/6f21a3b50a0e3b04dc78554aa6e199ed6b47b54b
